language: csharp
solution: "./Web_app/Web_app.sln"
mono: none
dotnet: 2.0.0
build: trusty
jobs:
  include:
  - stage: build
    script: dotnet build "./Web_app"
  - stage: test
    script: dotnet test "./Web_app/TestProject"
  - stage: deploy
    script: skip
    deploy:
      provider: heroku
	  app : webserver11bld
      api_key:
        secure: 76026dcf-9ddf-47a6-9d6e-c8fa16980160
	  strategy: git
	  