language: csharp
solution: "./Web_app/Web_app.sln"
mono: none
dotnet: 2.0.0
build: trusty
jobs:
  include:
  - stage: build
    script: dotnet build "./Web_app"
  - stage: test
    script: dotnet test "./Web_app/TestProject"
  - stage: deploy
    script: skip
    deploy:
      provider: heroku
      api_key:
        secure: fnD/bGoMM4mfw0ql+BWe7+2SWLqI6c0PiGDEY+LOIweFIGAW5Vb8zi7wcRu8VKC9w7qwHConM2HcE36iiDiLiEHIYWhNCLA61taPs5x6I9pNrlZ9hCn3nkMPDfIWjXrkbupcitzu24kqlXslUwR6Pu+AFf863I2XoFeTwIW2feDuK0Q3fIRQNeuMNovh708ufcBdgpF4ocCgIxyay0hChfist2hgYDDtGZ4epbljJPHQmf7HmCFYpbGVpAvqSYtVfWavFfaL5ejzOZ4a2hYzxqFy7oDPFXmUOzqGN4prGxxlxZ86iBFy3WGl+gORGkYK9E9YvdXM+LiXTGzWB6qAxgLaCzD9WXebcmxHpozQAKbJi1mXHNKb5weJLxcjAGP/2ra9ZWHaeyWXcQ+EXMUfaJ+cx8cu53RSDu7UrydfXVP3LhOwDKaezezyZnR+U6LhEJz9s26LBLvTwmWTMpmKa9mpxQ3dwh5GHJp/z2kJpA7LiEQjODIZ4RRe1gUlmI7ciF3cZ09zXpU3h0eoAHzuxD4L8qPTpBNrojBPwp9IrMy6cDRxTUL3OpA1Mot/lOGs6XkKoy+06sR7l1wvWeIzwwobJ96NtGH/tjI1UK3nbzObvpq+4PYVIZeGSdWJjxBWdeKaYrigy550Bnvw0fKPF1rQtH++k1p1/kM3CRsvdVk=
