language: csharp
solution: Web_app.sln
mono: none
dotnet: 2.0.0
build: trusty
jobs:
  include:
    - stage: build
      script: ./scripts/linux/build.sh
    - stage: test
      script: ./scripts/linux/test.sh
    - stage: deploy
      script: skip
      deploy:
        provider: heroku
        api_key:
          secure: 76026dcf-9ddf-47a6-9d6e-c8fa16980160

